[package]
name = "table-top-down-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quircs = "0.10.0"
image = "^0.24"
ndarray = "^0.15"
num-traits = "^0.2"